### ISSUE TITLE
Refresh access tokens

### ISSUE THREAD

**Issue by alastairs** [waives/waives.net#10]
**Is your feature request related to a problem? Please describe.**
Access tokens will expire after 24 hours. Long-running apps will need re-authenticate within that window to ensure continued operation; otherwise a restart of the application will be required. 

**Describe the solution you'd like**
I think the easiest solution to implement is to automatically refresh the token on a deadline-based system, e.g. every 12 hours. When a `Login()` call is made, a deadline is set on the `WaivesClient` of 12 hours hence, and this is compared with the current time on each request. When the deadline is passed, `Login()` is run again.

**Describe alternatives you've considered**
Alternative approaches include:
 - parsing the access token to identify its expiry, and renewing before then. The `System.IdentityModel.Tokens.Jwt` package would help with this. 
 - a timer-based implementation of the deadline approach described above

**Additional context**
All these approaches require maintaining the consumer's API client ID and secret in memory in order to issue future requests for access tokens; we need to consider ways of securely storing this sensitive data.

**Comment by phildrip** [comment]
In `surf` we have a `TokenRetriever` interface, which is decorated by a `TokenCache` (it also implements the `TokenRetriever` interface: https://github.com/CloudHub360/ch360.go/blob/master/auth/httptokencache.go

The `TokenCache` checks its cached access token every time `RetrieveToken` is called (which is for every http request). If its cached token is due to expire within 1 minute, it requests a new one, caches it and returns it to the caller.

**Comment by alastairs** [comment]
Fixed by #72 and #73.
